CREATE TABLE knowledge_documents (
    id VARCHAR(160) NOT NULL,
    evidence_id VARCHAR(128) NOT NULL,
    product_id CHAR(26) NOT NULL,
    sku_id CHAR(26) NULL,
    category_id CHAR(26) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    topic VARCHAR(64) NOT NULL,
    sentiment VARCHAR(16) NULL,
    trust_level DECIMAL(5,4) NOT NULL,
    published_at DATETIME(3) NOT NULL,
    content TEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    embedding_model VARCHAR(64) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL,
    injection_flag TINYINT(1) NOT NULL DEFAULT 0,
    dataset_version VARCHAR(64) NOT NULL,
    is_simulated TINYINT(1) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_knowledge_documents_evidence UNIQUE (evidence_id),
    CONSTRAINT fk_knowledge_documents_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_knowledge_documents_sku FOREIGN KEY (sku_id) REFERENCES skus (id),
    CONSTRAINT fk_knowledge_documents_category FOREIGN KEY (category_id) REFERENCES categories (id),
    INDEX idx_knowledge_documents_product_topic (product_id, topic),
    INDEX idx_knowledge_documents_sku_topic (sku_id, topic),
    INDEX idx_knowledge_documents_dataset (dataset_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
